services:
  postgres:
    image: postgres:15-alpine
    container_name: unitech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: unitech_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: